### ISSUE TITLE
Very Poor `ImmVision::Image` Performance

### ISSUE THREAD

**Issue by RushOnline** [pthom/immvision#11]
When using the `ImmVision::Image` function, performance drops significantly, causing a huge CPU load when switching images, as well as when moving and scaling the image.

The source image changes 10 times per second (this is a video from a camera).

```yaml
Display Image: RGB 8-bit, 4656x3496 (16Mpx), changes 10 times per second.
OS: Windows, Linux (no matter).
CPU: AMD Ryzen 7 5800X 8-Core @ 2.2GHz
RAM: 32GB
GPU: GeForce GTX 1080 Ti (11GB VRAM)
Framerate can drop to: 25fps
```

On weaker computers (3rd-4th generation Intel Core i7), the frame rate drops to 0.8-1.5 FPS.

Could you please suggest how to improve performance? Which part of the code do you think is the most resource-intensive?
